RestClients:
  #Preconfigured for the Docker Based Community Edition running on localhost port 8080
  #Admin Url: https//localhost:8080/share
  #Swagger openApi: https://api-explorer.alfresco.com/api-explorer/definitions/alfresco-core.json
  Alfresco (Alfresco Content Services):
    UUID: f0cc7209-7cdd-4a5d-9dde-72257a4bf963
    Url: http://localhost:8080/alfresco/api/-default-/public/alfresco/versions/1
    Icon: res:/webContent/icons/alfresco-logo.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - ch.ivyteam.ivy.rest.client.authentication.HttpBasicAuthenticationFeature
    - org.glassfish.jersey.media.multipart.MultiPartFeature
    Properties:
      JSON.Deserialization.FAIL_ON_UNKNOWN_PROPERTIES: 'false'
      username: admin
      password: ${decrypt:\u0075\u0070\u00A9\u00EF\u009C\u0075\u0055\u0041\u0008\u0098\u005E\u0085\u00B2\u000D\u00E2\u00E3\u0097\u0089\u007D\u0054\u002D\u0058\u006C\u002D\u00B0\u0087\u00ED\u004E\u00ED\u00B0\u005A\u002D}
