/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alfresco.api.explorer;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ActionBodyExec
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-22T12:37:25.271534100+02:00[Europe/Berlin]")
public class ActionBodyExec {
  @JsonProperty("actionDefinitionId")
  private String actionDefinitionId = null;

  @JsonProperty("targetId")
  private String targetId = null;

  @JsonProperty("params")
  private Object params = null;

  public ActionBodyExec actionDefinitionId(String actionDefinitionId) {
    this.actionDefinitionId = actionDefinitionId;
    return this;
  }

   /**
   * Get actionDefinitionId
   * @return actionDefinitionId
  **/
  public String getActionDefinitionId() {
    return actionDefinitionId;
  }

  public void setActionDefinitionId(String actionDefinitionId) {
    this.actionDefinitionId = actionDefinitionId;
  }

  public ActionBodyExec targetId(String targetId) {
    this.targetId = targetId;
    return this;
  }

   /**
   * The entity upon which to execute the action, typically a node ID or similar.
   * @return targetId
  **/
  public String getTargetId() {
    return targetId;
  }

  public void setTargetId(String targetId) {
    this.targetId = targetId;
  }

  public ActionBodyExec params(Object params) {
    this.params = params;
    return this;
  }

   /**
   * Get params
   * @return params
  **/
  public Object getParams() {
    return params;
  }

  public void setParams(Object params) {
    this.params = params;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionBodyExec actionBodyExec = (ActionBodyExec) o;
    return Objects.equals(this.actionDefinitionId, actionBodyExec.actionDefinitionId) &&
        Objects.equals(this.targetId, actionBodyExec.targetId) &&
        Objects.equals(this.params, actionBodyExec.params);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionDefinitionId, targetId, params);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionBodyExec {\n");
    
    sb.append("    actionDefinitionId: ").append(toIndentedString(actionDefinitionId)).append("\n");
    sb.append("    targetId: ").append(toIndentedString(targetId)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
