/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alfresco.api.explorer;

import java.util.Objects;
import java.util.Arrays;
import com.alfresco.api.explorer.ContentInfo;
import com.alfresco.api.explorer.Definition;
import com.alfresco.api.explorer.Node;
import com.alfresco.api.explorer.PathInfo;
import com.alfresco.api.explorer.PermissionsInfo;
import com.alfresco.api.explorer.UserInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.List;
/**
 * DeletedNode
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-22T12:37:25.271534100+02:00[Europe/Berlin]")
public class DeletedNode extends Node {
  @JsonProperty("archivedByUser")
  private UserInfo archivedByUser = null;

  @JsonProperty("archivedAt")
  private OffsetDateTime archivedAt = null;

  public DeletedNode archivedByUser(UserInfo archivedByUser) {
    this.archivedByUser = archivedByUser;
    return this;
  }

   /**
   * Get archivedByUser
   * @return archivedByUser
  **/
  public UserInfo getArchivedByUser() {
    return archivedByUser;
  }

  public void setArchivedByUser(UserInfo archivedByUser) {
    this.archivedByUser = archivedByUser;
  }

  public DeletedNode archivedAt(OffsetDateTime archivedAt) {
    this.archivedAt = archivedAt;
    return this;
  }

   /**
   * Get archivedAt
   * @return archivedAt
  **/
  public OffsetDateTime getArchivedAt() {
    return archivedAt;
  }

  public void setArchivedAt(OffsetDateTime archivedAt) {
    this.archivedAt = archivedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeletedNode deletedNode = (DeletedNode) o;
    return Objects.equals(this.archivedByUser, deletedNode.archivedByUser) &&
        Objects.equals(this.archivedAt, deletedNode.archivedAt) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archivedByUser, archivedAt, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeletedNode {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    archivedByUser: ").append(toIndentedString(archivedByUser)).append("\n");
    sb.append("    archivedAt: ").append(toIndentedString(archivedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
