/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alfresco.api.explorer;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * DirectAccessUrlBodyCreate
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-22T12:37:25.271534100+02:00[Europe/Berlin]")
public class DirectAccessUrlBodyCreate {
  @JsonProperty("expiresAt")
  private OffsetDateTime expiresAt = null;

  @JsonProperty("validFor")
  private Integer validFor = null;

  public DirectAccessUrlBodyCreate expiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Get expiresAt
   * @return expiresAt
  **/
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }

  public DirectAccessUrlBodyCreate validFor(Integer validFor) {
    this.validFor = validFor;
    return this;
  }

   /**
   * The length of time in seconds that the url is valid for. 
   * minimum: 1
   * @return validFor
  **/
  public Integer getValidFor() {
    return validFor;
  }

  public void setValidFor(Integer validFor) {
    this.validFor = validFor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DirectAccessUrlBodyCreate directAccessUrlBodyCreate = (DirectAccessUrlBodyCreate) o;
    return Objects.equals(this.expiresAt, directAccessUrlBodyCreate.expiresAt) &&
        Objects.equals(this.validFor, directAccessUrlBodyCreate.validFor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expiresAt, validFor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DirectAccessUrlBodyCreate {\n");
    
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    validFor: ").append(toIndentedString(validFor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
