/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alfresco.api.explorer;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Download
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-22T12:37:25.271534100+02:00[Europe/Berlin]")
public class Download {
  @JsonProperty("filesAdded")
  private Integer filesAdded = null;

  @JsonProperty("bytesAdded")
  private Integer bytesAdded = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("totalFiles")
  private Integer totalFiles = null;

  @JsonProperty("totalBytes")
  private Integer totalBytes = null;

  /**
   * the current status of the download node creation
   */
  public enum StatusEnum {
    PENDING("PENDING"),
    CANCELLED("CANCELLED"),
    IN_PROGRESS("IN_PROGRESS"),
    DONE("DONE"),
    MAX_CONTENT_SIZE_EXCEEDED("MAX_CONTENT_SIZE_EXCEEDED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = StatusEnum.PENDING;

  public Download filesAdded(Integer filesAdded) {
    this.filesAdded = filesAdded;
    return this;
  }

   /**
   * number of files added so far in the zip
   * @return filesAdded
  **/
  public Integer getFilesAdded() {
    return filesAdded;
  }

  public void setFilesAdded(Integer filesAdded) {
    this.filesAdded = filesAdded;
  }

  public Download bytesAdded(Integer bytesAdded) {
    this.bytesAdded = bytesAdded;
    return this;
  }

   /**
   * number of bytes added so far in the zip
   * @return bytesAdded
  **/
  public Integer getBytesAdded() {
    return bytesAdded;
  }

  public void setBytesAdded(Integer bytesAdded) {
    this.bytesAdded = bytesAdded;
  }

  public Download id(String id) {
    this.id = id;
    return this;
  }

   /**
   * the id of the download node
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Download totalFiles(Integer totalFiles) {
    this.totalFiles = totalFiles;
    return this;
  }

   /**
   * the total number of files to be added in the zip
   * @return totalFiles
  **/
  public Integer getTotalFiles() {
    return totalFiles;
  }

  public void setTotalFiles(Integer totalFiles) {
    this.totalFiles = totalFiles;
  }

  public Download totalBytes(Integer totalBytes) {
    this.totalBytes = totalBytes;
    return this;
  }

   /**
   * the total number of bytes to be added in the zip
   * @return totalBytes
  **/
  public Integer getTotalBytes() {
    return totalBytes;
  }

  public void setTotalBytes(Integer totalBytes) {
    this.totalBytes = totalBytes;
  }

  public Download status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * the current status of the download node creation
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Download download = (Download) o;
    return Objects.equals(this.filesAdded, download.filesAdded) &&
        Objects.equals(this.bytesAdded, download.bytesAdded) &&
        Objects.equals(this.id, download.id) &&
        Objects.equals(this.totalFiles, download.totalFiles) &&
        Objects.equals(this.totalBytes, download.totalBytes) &&
        Objects.equals(this.status, download.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filesAdded, bytesAdded, id, totalFiles, totalBytes, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Download {\n");
    
    sb.append("    filesAdded: ").append(toIndentedString(filesAdded)).append("\n");
    sb.append("    bytesAdded: ").append(toIndentedString(bytesAdded)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    totalFiles: ").append(toIndentedString(totalFiles)).append("\n");
    sb.append("    totalBytes: ").append(toIndentedString(totalBytes)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
