/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alfresco.api.explorer;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * A favorite describes an Alfresco entity that a person has marked as a favorite. The target can be a site, file or folder. 
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-22T12:37:25.271534100+02:00[Europe/Berlin]")
public class Favorite {
  @JsonProperty("targetGuid")
  private String targetGuid = null;

  @JsonProperty("createdAt")
  private OffsetDateTime createdAt = null;

  @JsonProperty("target")
  private Object target = null;

  @JsonProperty("properties")
  private Object properties = null;

  public Favorite targetGuid(String targetGuid) {
    this.targetGuid = targetGuid;
    return this;
  }

   /**
   * The guid of the object that is a favorite.
   * @return targetGuid
  **/
  public String getTargetGuid() {
    return targetGuid;
  }

  public void setTargetGuid(String targetGuid) {
    this.targetGuid = targetGuid;
  }

  public Favorite createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The time the object was made a favorite.
   * @return createdAt
  **/
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Favorite target(Object target) {
    this.target = target;
    return this;
  }

   /**
   * Get target
   * @return target
  **/
  public Object getTarget() {
    return target;
  }

  public void setTarget(Object target) {
    this.target = target;
  }

  public Favorite properties(Object properties) {
    this.properties = properties;
    return this;
  }

   /**
   * A subset of the target favorite properties, system properties and properties already available in the target are excluded.
   * @return properties
  **/
  public Object getProperties() {
    return properties;
  }

  public void setProperties(Object properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Favorite favorite = (Favorite) o;
    return Objects.equals(this.targetGuid, favorite.targetGuid) &&
        Objects.equals(this.createdAt, favorite.createdAt) &&
        Objects.equals(this.target, favorite.target) &&
        Objects.equals(this.properties, favorite.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetGuid, createdAt, target, properties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Favorite {\n");
    
    sb.append("    targetGuid: ").append(toIndentedString(targetGuid)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
