/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alfresco.api.explorer;

import java.util.Objects;
import java.util.Arrays;
import com.alfresco.api.explorer.Node;
import com.alfresco.api.explorer.NodeChildAssociationEntry;
import com.alfresco.api.explorer.Pagination;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * NodeChildAssociationPagingList
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-22T12:37:25.271534100+02:00[Europe/Berlin]")
public class NodeChildAssociationPagingList {
  @JsonProperty("pagination")
  private Pagination pagination = null;

  @JsonProperty("entries")
  private List<NodeChildAssociationEntry> entries = null;

  @JsonProperty("source")
  private Node source = null;

  public NodeChildAssociationPagingList pagination(Pagination pagination) {
    this.pagination = pagination;
    return this;
  }

   /**
   * Get pagination
   * @return pagination
  **/
  public Pagination getPagination() {
    return pagination;
  }

  public void setPagination(Pagination pagination) {
    this.pagination = pagination;
  }

  public NodeChildAssociationPagingList entries(List<NodeChildAssociationEntry> entries) {
    this.entries = entries;
    return this;
  }

  public NodeChildAssociationPagingList addEntriesItem(NodeChildAssociationEntry entriesItem) {
    if (this.entries == null) {
      this.entries = new ArrayList<>();
    }
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  public List<NodeChildAssociationEntry> getEntries() {
    return entries;
  }

  public void setEntries(List<NodeChildAssociationEntry> entries) {
    this.entries = entries;
  }

  public NodeChildAssociationPagingList source(Node source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  public Node getSource() {
    return source;
  }

  public void setSource(Node source) {
    this.source = source;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeChildAssociationPagingList nodeChildAssociationPagingList = (NodeChildAssociationPagingList) o;
    return Objects.equals(this.pagination, nodeChildAssociationPagingList.pagination) &&
        Objects.equals(this.entries, nodeChildAssociationPagingList.entries) &&
        Objects.equals(this.source, nodeChildAssociationPagingList.source);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pagination, entries, source);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeChildAssociationPagingList {\n");
    
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
