/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alfresco.api.explorer;

import java.util.Objects;
import java.util.Arrays;
import com.alfresco.api.explorer.PermissionElement;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * PermissionsBody
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-22T12:37:25.271534100+02:00[Europe/Berlin]")
public class PermissionsBody {
  @JsonProperty("isInheritanceEnabled")
  private Boolean isInheritanceEnabled = null;

  @JsonProperty("locallySet")
  private List<PermissionElement> locallySet = null;

  public PermissionsBody isInheritanceEnabled(Boolean isInheritanceEnabled) {
    this.isInheritanceEnabled = isInheritanceEnabled;
    return this;
  }

   /**
   * Get isInheritanceEnabled
   * @return isInheritanceEnabled
  **/
  public Boolean isIsInheritanceEnabled() {
    return isInheritanceEnabled;
  }

  public void setIsInheritanceEnabled(Boolean isInheritanceEnabled) {
    this.isInheritanceEnabled = isInheritanceEnabled;
  }

  public PermissionsBody locallySet(List<PermissionElement> locallySet) {
    this.locallySet = locallySet;
    return this;
  }

  public PermissionsBody addLocallySetItem(PermissionElement locallySetItem) {
    if (this.locallySet == null) {
      this.locallySet = new ArrayList<>();
    }
    this.locallySet.add(locallySetItem);
    return this;
  }

   /**
   * Get locallySet
   * @return locallySet
  **/
  public List<PermissionElement> getLocallySet() {
    return locallySet;
  }

  public void setLocallySet(List<PermissionElement> locallySet) {
    this.locallySet = locallySet;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PermissionsBody permissionsBody = (PermissionsBody) o;
    return Objects.equals(this.isInheritanceEnabled, permissionsBody.isInheritanceEnabled) &&
        Objects.equals(this.locallySet, permissionsBody.locallySet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isInheritanceEnabled, locallySet);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PermissionsBody {\n");
    
    sb.append("    isInheritanceEnabled: ").append(toIndentedString(isInheritanceEnabled)).append("\n");
    sb.append("    locallySet: ").append(toIndentedString(locallySet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
