/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alfresco.api.explorer;

import java.util.Objects;
import java.util.Arrays;
import com.alfresco.api.explorer.PermissionElement;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * PermissionsInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-22T12:37:25.271534100+02:00[Europe/Berlin]")
public class PermissionsInfo {
  @JsonProperty("isInheritanceEnabled")
  private Boolean isInheritanceEnabled = null;

  @JsonProperty("inherited")
  private List<PermissionElement> inherited = null;

  @JsonProperty("locallySet")
  private List<PermissionElement> locallySet = null;

  @JsonProperty("settable")
  private List<String> settable = null;

  public PermissionsInfo isInheritanceEnabled(Boolean isInheritanceEnabled) {
    this.isInheritanceEnabled = isInheritanceEnabled;
    return this;
  }

   /**
   * Get isInheritanceEnabled
   * @return isInheritanceEnabled
  **/
  public Boolean isIsInheritanceEnabled() {
    return isInheritanceEnabled;
  }

  public void setIsInheritanceEnabled(Boolean isInheritanceEnabled) {
    this.isInheritanceEnabled = isInheritanceEnabled;
  }

  public PermissionsInfo inherited(List<PermissionElement> inherited) {
    this.inherited = inherited;
    return this;
  }

  public PermissionsInfo addInheritedItem(PermissionElement inheritedItem) {
    if (this.inherited == null) {
      this.inherited = new ArrayList<>();
    }
    this.inherited.add(inheritedItem);
    return this;
  }

   /**
   * Get inherited
   * @return inherited
  **/
  public List<PermissionElement> getInherited() {
    return inherited;
  }

  public void setInherited(List<PermissionElement> inherited) {
    this.inherited = inherited;
  }

  public PermissionsInfo locallySet(List<PermissionElement> locallySet) {
    this.locallySet = locallySet;
    return this;
  }

  public PermissionsInfo addLocallySetItem(PermissionElement locallySetItem) {
    if (this.locallySet == null) {
      this.locallySet = new ArrayList<>();
    }
    this.locallySet.add(locallySetItem);
    return this;
  }

   /**
   * Get locallySet
   * @return locallySet
  **/
  public List<PermissionElement> getLocallySet() {
    return locallySet;
  }

  public void setLocallySet(List<PermissionElement> locallySet) {
    this.locallySet = locallySet;
  }

  public PermissionsInfo settable(List<String> settable) {
    this.settable = settable;
    return this;
  }

  public PermissionsInfo addSettableItem(String settableItem) {
    if (this.settable == null) {
      this.settable = new ArrayList<>();
    }
    this.settable.add(settableItem);
    return this;
  }

   /**
   * Get settable
   * @return settable
  **/
  public List<String> getSettable() {
    return settable;
  }

  public void setSettable(List<String> settable) {
    this.settable = settable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PermissionsInfo permissionsInfo = (PermissionsInfo) o;
    return Objects.equals(this.isInheritanceEnabled, permissionsInfo.isInheritanceEnabled) &&
        Objects.equals(this.inherited, permissionsInfo.inherited) &&
        Objects.equals(this.locallySet, permissionsInfo.locallySet) &&
        Objects.equals(this.settable, permissionsInfo.settable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isInheritanceEnabled, inherited, locallySet, settable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PermissionsInfo {\n");
    
    sb.append("    isInheritanceEnabled: ").append(toIndentedString(isInheritanceEnabled)).append("\n");
    sb.append("    inherited: ").append(toIndentedString(inherited)).append("\n");
    sb.append("    locallySet: ").append(toIndentedString(locallySet)).append("\n");
    sb.append("    settable: ").append(toIndentedString(settable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
