/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alfresco.api.explorer;

import java.util.Objects;
import java.util.Arrays;
import com.alfresco.api.explorer.Pagination;
import com.alfresco.api.explorer.SiteMembershipRequestWithPersonEntry;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * SiteMembershipRequestWithPersonPagingList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-22T12:37:25.271534100+02:00[Europe/Berlin]")
public class SiteMembershipRequestWithPersonPagingList {
  @JsonProperty("pagination")
  private Pagination pagination = null;

  @JsonProperty("entries")
  private List<SiteMembershipRequestWithPersonEntry> entries = new ArrayList<>();

  public SiteMembershipRequestWithPersonPagingList pagination(Pagination pagination) {
    this.pagination = pagination;
    return this;
  }

   /**
   * Get pagination
   * @return pagination
  **/
  public Pagination getPagination() {
    return pagination;
  }

  public void setPagination(Pagination pagination) {
    this.pagination = pagination;
  }

  public SiteMembershipRequestWithPersonPagingList entries(List<SiteMembershipRequestWithPersonEntry> entries) {
    this.entries = entries;
    return this;
  }

  public SiteMembershipRequestWithPersonPagingList addEntriesItem(SiteMembershipRequestWithPersonEntry entriesItem) {
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  public List<SiteMembershipRequestWithPersonEntry> getEntries() {
    return entries;
  }

  public void setEntries(List<SiteMembershipRequestWithPersonEntry> entries) {
    this.entries = entries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SiteMembershipRequestWithPersonPagingList siteMembershipRequestWithPersonPagingList = (SiteMembershipRequestWithPersonPagingList) o;
    return Objects.equals(this.pagination, siteMembershipRequestWithPersonPagingList.pagination) &&
        Objects.equals(this.entries, siteMembershipRequestWithPersonPagingList.entries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pagination, entries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SiteMembershipRequestWithPersonPagingList {\n");
    
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
