Variables:
  # Custom variables of Alfresco Content Services API for environment dev_axonivy used for testing
  Alfresco:
    # Username for "Alfresco Content Service"
    Username: 'admin'

    # The endpoint uri of the rest service. Adressing local mock service
    EndpointUri: 'http://{ivy.engine.host}:{ivy.engine.http.port}/{ivy.request.application}/api/ecmMock'

    # The password for "Alfresco Content Service".
    Password: '${encrypt:admin}'

