name: CI-Build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '21 21 * * *'

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v4
    with:
      mvnArgs: '-Dmaven.test.failure.ignore=true'

