name: CI-Build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '21 21 * * *'

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v4
